# Generated by Django 5.1.6 on 2025-02-24 08:57

import book_list_manager.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('publication_date', models.DateField(validators=[book_list_manager.models.publication_date_validator])),
                ('isbn', models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must be exactly 10 or 13 digits.', regex='^\\d{10}|\\d{13}$')])),
            ],
        ),
    ]
