# Generated by Django 5.1.6 on 2025-02-24 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must be exactly 10 or 13 digits.', regex='^\\d{10}|\\d{13}$')]),
        ),
    ]
